### ISSUE TITLE
Non-human genomic data

### ISSUE THREAD

**Issue by sapoudel** [gosling-lang/gos#102]
Hey, 
Just learned about gosling and am trying to play around with it using data from bacteria. How can I pass coordinates from my own bacterial assembly? I tried passing `assembly='unknown'` to track, but nothing renders when I do that. 

I am currently using gos on jupyter notebook.

**Comment by manzt** [comment]
Hi! Thanks for checking out the project and for your patience in my response. We just added support for custom assemblies to Gosling.js recently (and it is now supported in Gos as of v0.0.11).

To do this, pass the assembly as a list of `(name, size)` tuples to `assembly`.

```python
gos.Track(data).mark_rect().encode(...).view(
  assembly=[
    ("chr1", 100_000),
    # ^ name    ^ size
  ]
)
```

I've added an [example](https://gosling-lang.github.io/gos/gallery/covid.html) to the documentation as well.

**Comment by sapoudel** [comment]
That is amazing! Thank you for the updated docs too. Really looking forward to using this tool!

**Comment by prheger** [comment]
Thanks for adding support for custom assemblies to gosling. I think a lot of people will appreciate this after gosling has been mentioned in Nature recently :-) I'm looking forward to give it a try :-)
