### ISSUE TITLE
Example gallery all empty

### ISSUE THREAD

**Issue by xtYao** [gosling-lang/gos#147]
https://gosling-lang.github.io/gos/gallery/bar_chart.html there is no visuals on the website and locally running the code produced the same blank output. Please investigate.

**Comment by sehilyi** [comment]
Thank you for submitting an issue! It looks like the `resgen` server (a data server used in the example) has a certification issue at the moment. If you replace the data with `https://server.gosling-lang.org/api/v1/tileset_info/?d=cistrome-multivec` (which is a dataset used in our [Gosling editor examples](https://gosling.js.org/)), you should be able to see visuals.

```diff
data = gos.multivec(
-   url="https://resgen.io/api/v1/tileset_info/?d=UvVPeLHuRDiYA3qwFlm7xQ",
+   url="https://server.gosling-lang.org/api/v1/tileset_info/?d=cistrome-multivec",
    row="sample",
    column="position",
    value="peak",
    categories=["sample 1"],
    binSize=5,
)
```
