### ISSUE TITLE
Support chromesizes for bigwig tile server in `data.vector`?

### ISSUE THREAD

**Issue by manzt** [gosling-lang/gos#42]
Do you by any chance know if a bigwig file can be used directly without any pre-aggregation using `vector()`? It looked so according to the [HiGlass docs](https://docs.higlass.io/data_preparation.html#bigwig-files), but when I tested with a local bigwig file, it did not show any visual elements in the rendered track, having some error message.

```py
v = vector(
    "../data/Astrocytes-insertions_bin100_RIPnorm.bw",
    value="value",
    column="position",
    binSize=4
)

gos.Track(v).mark_bar(outlineWidth=0).encode(
    x="position:G",
    y=gos.Channel("value:Q"),
    color=gos.Channel("value:Q", legend=True),
    stroke=gos.value("black"),
    strokeWidth=gos.value(0.3),
).view() # Uncaught (in promise) TypeError: Cannot read property 'chromsizes' of null
```

I wonder if `chromsizes` should be somehow provided before storing a bigwig file to the server.

> If a coordSystem is specified for the bigWig, but no chromsizes are found on the server, the import will fail.

_Originally posted by @sehilyi in https://github.com/manzt/gos/pull/39#discussion_r695857459_

**Comment by liuyangzzu** [comment]
Hi all, I got the below error, the UI can not be rendered:
![Screen Shot 2021-11-07 at 12 01 10](https://user-images.githubusercontent.com/14856363/140654445-68059390-d1de-4312-bda1-7feb7031b9f5.png)

**Comment by manzt** [comment]
Thank you for voicing this error! Using bigwig `vector` tilesets is still somewhat challenging in gos because we will need to expand the API to allow for more configuration of the server (i.e. chromsizes). However, I notice the file format you are using appears to be `bigwig`. 

We have direct client support for bigwig files using the `gos.bigwig` function, so I'm curious if that would work in this context. cc: @sehilyi 

```python
import gosling as gos # version 0.0.6

na19240_megalodon_fn = "/path/to/data/NA19240_Megalodon.bw"

v = gos.bigwig(na19240_megalodon_fn, ...)

gos.Track(v).mark_bar(outlineWidth=0).encode(...).view()
```

**Comment by liuyangzzu** [comment]
Thank you manzt!
When I use bigwig in the internet, it is ok. However, when I download the bigwig file in local file, and set url to the local path. The figure can not be rendered. Is my local client not started, how can I figure out this problem? Thank you!

My running codes using internet URLs:
```
import gosling as gos

HFFc6_H3K4me3 = gos.bigwig(
    url="https://s3.amazonaws.com/gosling-lang.org/data/HFFc6_H3K4me3.bigWig",
    column="position",
    value="peak",
    binSize=8,
)
# Tracks & Views
track1 = gos.Track(HFFc6_H3K4me3).mark_bar().encode(
    x=gos.Channel("start:G", axis="top"),
    xe="end:G",
    y=gos.Channel("peak:Q", axis="none"),
    color=gos.value("darkgreen"),
).properties(title="HFFc6_H3K4me3", height=200, width=800)


gos.vertical(track1).properties(
    title="Visual Encoding",
    subtitle="Gosling provides diverse visual encoding methods",
    layout="linear",
    centerRadius=0.8,
    xDomain=gos.Domain(chromosome="1", interval=[1, 3000500]),
)

```
![Screen Shot 2021-11-07 at 14 27 09](https://user-images.githubusercontent.com/14856363/140659097-213898d5-2e93-4f1e-98d1-71a344aa2ad8.png)

Failed when I change to local file for URL:
```
HFFc6_H3K4me3 = gos.bigwig(
    url="/projects/li-lab/yang/HFFc6_H3K4me3.bigWig",
    column="position",
    value="peak",
    binSize=8,
)
```

![Screen Shot 2021-11-07 at 14 27 36](https://user-images.githubusercontent.com/14856363/140659094-3ee81498-6024-4f58-bd28-9d37ef39728d.png)

**Comment by manzt** [comment]
I'm sorry, but I'm not able to reproduce this issue. I downloaded the example locally as well, and am able host the visualization locally.

![image](https://user-images.githubusercontent.com/24403730/140662907-8aad932f-737d-4d4f-a5a0-f230aaa14c24.png)

Could you share what operating system you are using? The "Server: [unknown] tileset: [undefined]" in your screenshot makes me wonder if somehow the new dataset isn't being loaded correctly. These messages pop up when a higlass tileset URL is used, and typically not for a bigwig/bam/csv dataset directly.
