### ISSUE TITLE
feat: add `gosling.datasets`

### ISSUE THREAD

**Issue by manzt** [gosling-lang/gos#56]
It might be nice to add some convenience exports for reusable example datasets for gosling. This could remove some of the boilerplate in the examples for:

```diff
import gosling as gos
- from gosling.data import multivec
+ from gosling.datasets import cistrome_multivec


- data = multivec(
-    url="https://server.gosling-lang.org/api/v1/tileset_info/?d=cistrome-multivec",
-    row="sample",
-    column="position",
-    value="peak",
-    categories=["sample 1", "sample 2", "sample 3", "sample 4"],
-    binSize=5,
- )
- base_track = gos.Track(data, width=800, height=100)

+ base_track = gos.Track(cistrome_multivec, width=800, height=100)
```

**Comment by sehilyi** [comment]
A list of some public data URLs used in the js editor:

https://github.com/gosling-lang/gosling.js/blob/97befe6be38eaa64fc0f79ced194c8094d5bfd9b/src/editor/example/gosling-data.ts

**Comment by manzt** [comment]
Great, thank you! It would make sense to export the "complete" datasets (e.g. `{ "url": ..., "type": ..., ... }`), unless these urls can be interpreted differently.

**Comment by sehilyi** [comment]
Yes, I think it makes sense since those datasets are used across multiple examples with the same data configs. I guess one can use `cistrome['url']` to access the URL and use different configs.

**Comment by manzt** [comment]
In retrospect, I don't think we should have "magic" datasets in Gos. it somewhat obscures The use of the API, and might be confusing to new users. I'm going to close for now.
