### ISSUE TITLE
How to visualize my own data?

### ISSUE THREAD

**Issue by liuyangzzu** [gosling-lang/gos#80]
Dear gos,
I am going to visualize my own data (BED, bedgraph or bigwig), my data format is very simple. But I can not find from your document how to visualized a user's data. Thank you!

Data format of bedgraph:
chr1	10468	10469	1.000
chr1	10469	10470	0.667
chr1	10470	10471	1.000

Thank you!
Yang

**Comment by manzt** [comment]
Hi there! Thanks for opening the issue. For a simple columnar text file like you've described, I believe you'd use the `gos.csv` module. cc: @sehilyi


```python
import gosling as gos

data = gos.csv(
  "/path/to/data",
  separator="\t",
  headerNames=["chr", "start", "end", "value"],
  chromosomeField="chr",
  genomicFields=["start", "end"],
  quantitativeFields=["value"],
)
```

This function, `gos.csv` will detect that the file is a local file and serve the data to the gosling visualization automatically. You could also wrap this behavior in a funciton that you can reuse if you have many of the same file types:


```python
import gosling as gos

def bedgraph(url):
  return gos.csv(
    url=url,
    separator="\t",
    headerNames=["chr", "start", "end", "value"],
    chromosomeField="chr",
    genomicFields=["start", "end"],
    quantitativeFields=["value"],
  )


t1 = gos.Track(bedgraph('/my/file1')).encode(...)
t2 = gos.Track(bedgraph('/myfile2').encode(...)
```

**Comment by liuyangzzu** [comment]
Hi manzt, I am almost done. But there are still some issue for my code.
I use the following csv format as input, `head NA19240_Megalodon.csv`
```
chr	start	end	value
chr1	10468	10469	0.875
chr1	10469	10470	0.680
```

My code for csv is below:
```
import gosling as gos

infn = '/projects/li-lab/yang/results/2021-11-04/ucsc_bw_1/NA19240_Megalodon.csv'

na19240_chr1 = gos.csv(
  infn,
  separator="\t",
  headerNames=["chr", "start", "end", "value"],
  chromosomeField="chr",
  genomicFields=["start", "end"],
  quantitativeFields=["value"],
)

# Tracks & Views
track1 = gos.Track(na19240_chr1).mark_bar().encode(
    x=gos.Channel("start:G", axis="top"),
    xe="end:G",
    y=gos.Channel("value:Q", axis="none"),
    color=gos.value("darkgreen"),
).properties(title="na19240_chr1", height=100, width=600)


gos.vertical(track1).properties(
    title="Visual Encoding",
    subtitle="Gosling provides diverse visual encoding methods",
    layout="linear",
    centerRadius=0.8,
    xDomain=gos.Domain(chromosome="chr1", interval=[1, 3000500]),
)
```

This time, the plot is no error mesage, but I can not see my value columns in the figure. I have lots of data points for chr1 in the tsv.

**Comment by liuyangzzu** [comment]
Below is the attachment for 10K lines of the csv file:
[NA19240_Megalodon_n10k.csv](https://github.com/gosling-lang/gos/files/7492988/NA19240_Megalodon_n10k.csv)

**Comment by manzt** [comment]
Thanks for more information. Could you share what web-browser you are using? I wonder if this could be an issue that is browser dependent. I am able to load the file you have shared with the following:

```python
import gosling as gos

infn = '../test_notebooks/data/NA19240_Megalodon_n10k.csv'

na19240_chr1 = gos.csv(
  infn,
  separator="\t",
  headerNames=["chr", "start", "end", "value"],
  chromosomeField="chr",
  genomicFields=["start", "end"],
  quantitativeFields=["value"],
)

# Tracks & Views
track1 = gos.Track(na19240_chr1).mark_bar().encode(
    x=gos.Channel("start:G", axis="top"),
    xe="end:G",
    y=gos.Channel("value:Q", axis="none"),
    color=gos.value("darkgreen"),
).properties(title="na19240_chr1", height=100, width=600)


gos.vertical(track1).properties(
    title="Visual Encoding",
    subtitle="Gosling provides diverse visual encoding methods",
    layout="linear",
    centerRadius=0.8,
    xDomain=gos.Domain(chromosome="chr1", interval=[1, 3000500]),
)
```

![image](https://user-images.githubusercontent.com/24403730/140662703-0f96fd49-b1c1-4e92-a88f-100d1b4baed0.png)

**Comment by liuyangzzu** [comment]
I changed to use jupyter-lab (before using jupyter notebook on HPC, may be internet restriction), now it works, bigwig datatype also OK now. 

However, I have two bigwig data, I want them share the same chromosome axis for zoom in and out for comparison. Any ways to achieve this? Thank you!

I have two bigwig data:
```
import gosling as gos

na19240_fn = '/Users/liuya/Downloads/results/2021-11-06/NA19240_Megalodon.bw'

na19240_data = gos.bigwig(
    url=na19240_fn,
    column="position",
    value="peak",
    binSize=8,
)

na12878_fn = '/Users/liuya/Downloads/results/2021-11-06/NA12878_Megalodon.bw'

na12878_data = gos.bigwig(
    url=na12878_fn,
    column="position",
    value="peak",
    binSize=8,
)
```

**Now I have no idea of letting these two track share the same chromosome axis for zooming in and out.**
```
track_na19240 = gos.Track(na19240_data).mark_bar().encode(
        x="start:G",
        xe="end:G",
        y=gos.Channel("peak:Q", axis="none"),
        color=gos.value("#56B4E9")
    )
track_na19240.view()

track_na12878 = gos.Track(na12878_data).mark_bar().encode(
        x="start:G",
        xe="end:G",
        y=gos.Channel("peak:Q", axis="none"),
        color=gos.value("#CC79A7")
    )
track_na12878.view()
```

Combine in one figure:
```
gos.vertical(track_na19240, track_na12878).properties(
    title="Nanome pipeline genome-wide report",
    subtitle="Methylation level by Megalodon",
    layout="linear",
    centerRadius=0.8,
)
```

![Screen Shot 2021-11-07 at 21 16 25](https://user-images.githubusercontent.com/14856363/140674450-0a204ce7-aeb8-4188-a183-2144ff2ad02e.png)

**Comment by sehilyi** [comment]
Hi @liuyangzzu!

To use synchronous navigation across multiple tracks, you can either (1) make them a single view by stacking or (2) set the same `linkingId`.

**(1) Two tracks in a single view**

All the tracks that are grouped as a single view (either by stacking or overlaying) will be synchronized.

```diff
track_na19240 = gos.Track(na19240_data).mark_bar().encode(
        x="start:G",
        xe="end:G",
        y=gos.Channel("peak:Q", axis="none"),
        color=gos.value("#56B4E9")
    )
- track_na19240.view()

track_na12878 = gos.Track(na12878_data).mark_bar().encode(
        x="start:G",
        xe="end:G",
        y=gos.Channel("peak:Q", axis="none"),
        color=gos.value("#CC79A7")
    )
- track_na12878.view()

+ gos.stack(track_na19240, track_na12878)
```

**(2) Using `linkingId` between views**

Using the `linkingId`, the genomics axes of multiple views will be ___linked___, enabling the synchronized navigation.

```diff
track_na19240 = gos.Track(na19240_data).mark_bar().encode(
        x="start:G",
        xe="end:G",
        y=gos.Channel("peak:Q", axis="none"),
        color=gos.value("#56B4E9")
    )
-track_na19240.view()
+track_na19240.view(linkingId="custom-id-to-lock-bw-tracks")

track_na12878 = gos.Track(na12878_data).mark_bar().encode(
        x="start:G",
        xe="end:G",
        y=gos.Channel("peak:Q", axis="none"),
        color=gos.value("#CC79A7")
    )
-track_na12878.view()
+track_na12878.view(linkingId="custom-id-to-lock-bw-tracks")

gos.vertical(track_na19240, track_na12878).properties(
    title="Nanome pipeline genome-wide report",
    subtitle="Methylation level by Megalodon",
    layout="linear",
    centerRadius=0.8,
)
```

Reference example:
- [Comparative Matrices](https://gosling-lang.github.io/gos/gallery/comparative_matrices.html): This example uses the two aforementioned methods (i.e., stacking bigwig tracks and using `linkingId` between two matrices).
- [Linking w/ Brush](https://gosling-lang.github.io/gos/gallery/brushing_and_linking.html): Using the `lingkingId`, a brush and a line chart are linked.

**Comment by liuyangzzu** [comment]
Super great solutions, the codes work very well! Thank you!
